# Generated by Django 3.0.5 on 2020-05-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='last_send',
            field=models.DateTimeField(null=True),
        ),
    ]
