# Generated by Django 3.0.5 on 2020-05-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0002_auto_20200502_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='last_send',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
