# Generated by Django 3.0.5 on 2020-05-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0003_auto_20200502_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
